name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.1

      - env:
          SSH_PRIVATE_KEY: "${{secrets.SSH_PRIVATE_KEY}}"
        name: "Create SSH key"
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
        shell: bash

      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Use python"
        uses: actions/setup-python@v2

      - name: "Install markdown"
        run: sudo apt-get update && sudo apt-get install -y markdown

      - name: "Install stuff"
        run: sudo apt-get -y install python3-pip

      - name: "Install timezones stuff?"
        run: pip3 install tzdata pytz

      - name: "Install pelican"
        run: pip3 install pelican Markdown

      - name: "Install jinja markdown tag"
        run: pip3 install jinja_markdown

      - name: "Install yasha"
        run: pip3 install yasha

      - name: "make all"
        run: make all

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy
        uses: actions/deploy-pages@v4
        id: deployment
